---
title: "Environmental Justice Data"
format: html
---
Adding the necessary libraries:
```{r}
library(tidyverse)
library(sf)
library(here)
library(tmap)
```
Reading in the data
```{r}
# read in geodatabase of EJScreen data at the Census Block Group level
# also doesn't work with read_sf
ejscreen <- sf::st_read(here::here("data", "ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb")) 
```
Changing column names to lower_snake
```{r}
ejscreen <- janitor::clean_names(ejscreen)
```
I'm interested in looking at cancer rates and how they correlate to the percentage of low income individauls. 

Filtering for Los Angeles County 
```{r}
los_angeles <- ejscreen |> 
  filter(cnty_name == "Los Angeles County")
```
Testing how the different ids are mapped out
```{r}
los_angeles_id <- los_angeles |> 
  filter(between(id, "060371192013", "060371204001"))
```

Filtering to see what regions are associated 
Mapping 
```{r}
tm_shape(los_angeles_id)+
  tm_polygons(fill = "cancer",
              fill.scale = tm_scale(values = "brewer.YlOrBr")) 
  
```


```{r}
# filter to a state you are interested in
california <- ejscreen |> 
  dplyr::filter(ST_ABBREV == "CA") 

# filter to a county you are interested in
santa_barbara <- ejscreen |> 
  dplyr::filter(CNTY_NAME %in% c("Santa Barbara County"))

# find the average values for all variables within counties
california_counties <- aggregate(california, by = list(california$CNTY_NAME), FUN = mean)
```

